pipeline
{
  agent any
  stages{
    stage('build') {
      steps{
        echo "this is Build Stage"
      }
    }
    stage('test') {
      steps{
        echo "this is test Stage"
      }
    }
    stage('deploy') {
      steps{
        echo "this is deploy Stage"
      }
    }
  }
}